<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ReadThreadsTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    use DatabaseMigrations;

    public function setUp()
    {
        //调用工厂创建Thread模型数据
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    public function test_a_user_can_browse_threads()
    {
        //测试标题数据
        $this->get('/threads')
            ->assertSee($this->thread->title);
    }

    public function test_a_user_can_read_a_single_thread()
    {
        //测试单个话题
         $this->get($this->thread->path())
            ->assertSee($this->thread->title);
    }

    public function test_a_user_can_read_replies_that_are_associated_with_a_thread()
    {
        //如果存在thread
        //并且该Thread拥有回复
        $reply = factory('App\Reply')
            ->create(['thread_id' => $this->thread->id]);
        //那么当我们看该Thread时
        //我们也要看到回复
        $this->get($this->thread->path())
            ->assertSee($reply->body);
    }
}
